In [1]:
import pandas as pd

perguntas = pd.read_csv('stackoverflow_perguntas.csv')
perguntas.sample(10)

Perguntas           Tags
2275  O seguinte código faz um "fader de imagens" em...         jquery
5228  Preciso pegar o ID da DIV superior ao que o bo...         jquery
4396  Dúvida simples. Geralmente eu vejo essa sintax...        node.js
3538  Tenho um site multilinguagem utilizando Ajax, ...         html  
5     Vi esse vídeo (link abaixo) e gostaria de cons...          html 
2805  Estou tentando reordenar uma lista de itens, q...        jquery 
2760      CODE         Precisaria inserir no objeto ...        angular
2948  Tenho o seguinte código, que copia pedaços da ...           html
4244  Estou com uma tarefa em que preciso criar um r...  jquery html  
1108  Boa tarde galera, sou novo em Node.js e estou ...        node.js

In [2]:
print(len(perguntas))

5408


In [3]:
print(len(perguntas.Tags.unique()))

37


In [4]:
print(perguntas.Tags.unique())

['node.js' 'jquery' 'html' 'html angular ' 'html ' 'angular' 'angular '
 'jquery html  ' 'jquery ' 'jquery html' 'jquery html ' 'html angular'
 'angular node.js ' 'html  ' 'jquery html angular' 'node.js '
 'html jquery' 'html jquery ' 'jquery angular  ' 'html node.js' 'jquery  '
 'angular node.js' 'jquery angular' 'html node.js ' 'jquery node.js '
 'angular  ' 'jquery angular ' 'jquery html angular ' 'node.js html '
 ' node.js' 'node.js html' 'html angular  ' 'jquery node.js'
 'angular html' 'html angular  node.js' 'jquery html node.js'
 'html angular node.js']


In [5]:
lista_de_tags = list()
for tags in perguntas.Tags.unique():
    for tag in tags.split():
    if tag not in lista_de_tags:
      lista_de_tags.append(tag)
print(lista_de_tags)

['node.js', 'jquery', 'html', 'angular']


In [6]:
node_js = []
for linha_tag in perguntas.Tags:
    if 'node.js' in linha_tag:
        node_js.append(1)
    else:
        node_js.append(0)

perguntas['node.js']= node_js
perguntas

Perguntas           Tags  \
0     Possuo um projeto Node.js porém preciso criar ...        node.js   
1     Gostaria de fazer testes unitários no Node.js,...        node.js   
2     Como inverter a ordem com que o jQuery itera u...         jquery   
3     Eu tenho uma página onde pretendo utilizar um ...           html   
4     Como exibir os dados retornados do FireStore e...  html angular    
...                                                 ...            ...   
5403  Queria saber como pegar o total de cores de um...   jquery html    
5404  Boa noite, estou usando phonegap para fazer um...          html    
5405  Estou construindo um mini fórum, e nele, os us...    jquery html   
5406  Boa tarde,  Estou para desenvolver um site na ...           html   
5407  Estou fazendo um hotsite, ele é one page, e é ...    jquery html   

      node.js  
0           1  
1           1  
2           0  
3           0  
4           0  
...       ...  
5403        0  
5404        0  
5405        0  
5406        0  
5407        0  

[5408 rows x 3 columns]

In [7]:
def nova_coluna(lista_tags, dataframe, nome_tags):
      for tag in lista_tags:
        coluna=list()
        for linha_tag in dataframe[nome_tags]:
            if tag in linha_tag:
                coluna.append(1)
            else:
                coluna.append(0)
    dataframe[tag] = coluna
nova_coluna(lista_de_tags, perguntas, 'Tags')
perguntas

Perguntas           Tags  \
0     Possuo um projeto Node.js porém preciso criar ...        node.js   
1     Gostaria de fazer testes unitários no Node.js,...        node.js   
2     Como inverter a ordem com que o jQuery itera u...         jquery   
3     Eu tenho uma página onde pretendo utilizar um ...           html   
4     Como exibir os dados retornados do FireStore e...  html angular    
...                                                 ...            ...   
5403  Queria saber como pegar o total de cores de um...   jquery html    
5404  Boa noite, estou usando phonegap para fazer um...          html    
5405  Estou construindo um mini fórum, e nele, os us...    jquery html   
5406  Boa tarde,  Estou para desenvolver um site na ...           html   
5407  Estou fazendo um hotsite, ele é one page, e é ...    jquery html   

      node.js  jquery  html  angular  
0           1       0     0        0  
1           1       0     0        0  
2           0       1     0        0  
3           0       0     1        0  
4           0       0     1        1  
...       ...     ...   ...      ...  
5403        0       1     1        0  
5404        0       0     1        0  
5405        0       1     1        0  
5406        0       0     1        0  
5407        0       1     1        0  

[5408 rows x 6 columns]

In [8]:
lista_1 = [1,2]
lista_2=[5,4]

lista_zip = zip(lista_1,lista_2)
print(list(lista_zip))

[(1, 5), (2, 4)]


In [9]:
lista_zip_tags = list(zip(perguntas[lista_de_tags[0]],
                     perguntas[lista_de_tags[1]],
                     perguntas[lista_de_tags[2]],
                     perguntas[lista_de_tags[3]]))
perguntas['todas_tags']=lista_zip_tags

In [10]:
perguntas.head()

Perguntas           Tags  node.js  \
0  Possuo um projeto Node.js porém preciso criar ...        node.js        1   
1  Gostaria de fazer testes unitários no Node.js,...        node.js        1   
2  Como inverter a ordem com que o jQuery itera u...         jquery        0   
3  Eu tenho uma página onde pretendo utilizar um ...           html        0   
4  Como exibir os dados retornados do FireStore e...  html angular         0   

   jquery  html  angular    todas_tags  
0       0     0        0  (1, 0, 0, 0)  
1       0     0        0  (1, 0, 0, 0)  
2       1     0        0  (0, 1, 0, 0)  
3       0     1        0  (0, 0, 1, 0)  
4       0     1        1  (0, 0, 1, 1)

In [11]:
from sklearn.model_selection import train_test_split

perguntas_treino, perguntas_test, tags_treino, tags_test = train_test_split(
    perguntas.Perguntas,
    perguntas.todas_tags,
    test_size=0.2,
    random_state =123)

In [12]:
perguntas_treino

1577       array1 = [1,2,3];   array2 = ["um","dois","...
1927    Não sei se fui claro no título, mas quem é da ...
3409    Alguém sabe me dizer qual a melhor forma de re...
4606    Estou com problemas ao tentar validar campos d...
5237    Preciso copiar um valor de dentro de um CODE  ...
                              ...                        
5218    Tenho um sisteminha, para mudar o layout da pá...
4060    Como fazer alto scoll ao carregar a página?  E...
1346    Explicação:  Tenho uma CODE  pai que contém du...
3454    Estou querendo fazer um sistema onde eu iria t...
3582    Galera eu to com um problemão, ja pesquisei ba...
Name: Perguntas, Length: 4326, dtype: object

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer

vetorizar = TfidfVectorizer(max_features=5000, max_df=0.85)
vetorizar

TfidfVectorizer(max_df=0.85, max_features=5000)

In [14]:
vetorizar.fit(perguntas.Perguntas)

perguntas_treino_tfidf = vetorizar.transform(perguntas_treino)
perguntas_test_tfidf= vetorizar.transform(perguntas_test)
print(perguntas_treino_tfidf.shape)
print(perguntas_test_tfidf.shape)

(4326, 5000)
(1082, 5000)


In [15]:
# from sklearn.multiclass import OneVsRestClassifier
# from sklearn.linear_model import LogisticRegression

# regressao_logistica = LogisticRegression()
# classificador_onevsrest = OneVsRestClassifier(regressao_logistica)
# classificador_onevsrest.fit(perguntas_treino_tfidf, tags_treino)

# pandas to array

In [16]:
import numpy as np

tags_treino_array = np.asarray(list(tags_treino))
tags_teste_array = np.asarray(list(tags_test))
print(tags_teste_array)
print(tags_treino_array)

[[0 1 0 0]
 [0 0 1 0]
 [1 0 0 0]
 ...
 [0 1 0 0]
 [0 1 0 0]
 [0 0 0 1]]
[[0 1 0 0]
 [0 1 0 0]
 [0 0 1 0]
 ...
 [0 1 1 0]
 [0 0 1 0]
 [0 1 1 0]]


In [17]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression

regressao_logistica = LogisticRegression(solver = 'lbfgs')
classificador_onevsrest = OneVsRestClassifier(regressao_logistica)
classificador_onevsrest.fit(perguntas_treino_tfidf, tags_treino_array)

resultado_onevsrest = classificador_onevsrest.score(perguntas_test_tfidf, tags_teste_array)

print(f'resultado {resultado_onevsrest*100:.2f}%')

resultado 41.68%


In [18]:
perguntas.todas_tags.unique()

array([(1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 0, 1, 1),
       (0, 0, 0, 1), (0, 1, 1, 0), (1, 0, 0, 1), (0, 1, 1, 1),
       (0, 1, 0, 1), (1, 0, 1, 0), (1, 1, 0, 0), (1, 0, 1, 1),
       (1, 1, 1, 0)], dtype=object)

In [19]:
len(perguntas.todas_tags.unique())

13

In [20]:
from sklearn.metrics import hamming_loss

previsao_onevsrest = classificador_onevsrest.predict(perguntas_test_tfidf)
hamming_loss_onevsrest = hamming_loss(tags_teste_array, previsao_onevsrest)
print(f'hamming_loss {hamming_loss_onevsrest:.2f}')

hamming_loss 0.19


In [21]:
perguntas

Perguntas           Tags  \
0     Possuo um projeto Node.js porém preciso criar ...        node.js   
1     Gostaria de fazer testes unitários no Node.js,...        node.js   
2     Como inverter a ordem com que o jQuery itera u...         jquery   
3     Eu tenho uma página onde pretendo utilizar um ...           html   
4     Como exibir os dados retornados do FireStore e...  html angular    
...                                                 ...            ...   
5403  Queria saber como pegar o total de cores de um...   jquery html    
5404  Boa noite, estou usando phonegap para fazer um...          html    
5405  Estou construindo um mini fórum, e nele, os us...    jquery html   
5406  Boa tarde,  Estou para desenvolver um site na ...           html   
5407  Estou fazendo um hotsite, ele é one page, e é ...    jquery html   

      node.js  jquery  html  angular    todas_tags  
0           1       0     0        0  (1, 0, 0, 0)  
1           1       0     0        0  (1, 0, 0, 0)  
2           0       1     0        0  (0, 1, 0, 0)  
3           0       0     1        0  (0, 0, 1, 0)  
4           0       0     1        1  (0, 0, 1, 1)  
...       ...     ...   ...      ...           ...  
5403        0       1     1        0  (0, 1, 1, 0)  
5404        0       0     1        0  (0, 0, 1, 0)  
5405        0       1     1        0  (0, 1, 1, 0)  
5406        0       0     1        0  (0, 0, 1, 0)  
5407        0       1     1        0  (0, 1, 1, 0)  

[5408 rows x 7 columns]

In [22]:
perguntas.corr()

node.js    jquery      html   angular
node.js  1.000000 -0.321485 -0.273523 -0.101787
jquery  -0.321485  1.000000 -0.253977 -0.366269
html    -0.273523 -0.253977  1.000000 -0.286706
angular -0.101787 -0.366269 -0.286706  1.000000

In [ ]:
# pip install scikit-multilearn

In [30]:
from skmultilearn.problem_transform import ClassifierChain


classificador_cadeia = ClassifierChain(regressao_logistica)
classificador_cadeia.fit(perguntas_treino_tfidf, tags_treino_array)

resultado_cadeia = classificador_cadeia.score(perguntas_test_tfidf, tags_teste_array)

print(f'resultado {resultado_cadeia*100:.2f}%')
previsao_cadeia = classificador_cadeia.predict(perguntas_test_tfidf)
hamming_loss_cadeia = hamming_loss(tags_teste_array, previsao_cadeia)
print(f'hamming_loss {hamming_loss_cadeia:.2f}')

resultado 49.82%
hamming_loss 0.21


In [33]:
from skmultilearn.problem_transform import BinaryRelevance


classificador_br = BinaryRelevance(regressao_logistica)
classificador_br.fit(perguntas_treino_tfidf, tags_treino_array)

resultado_br = classificador_br.score(perguntas_test_tfidf, tags_teste_array)

print(f'resultado {resultado_br*100:.2f}%')
previsao_br = classificador_br.predict(perguntas_test_tfidf)
hamming_loss_br = hamming_loss(tags_teste_array, previsao_br)
print(f'hamming_loss {hamming_loss_br:.2f}')

resultado 41.68%
hamming_loss 0.19


In [39]:
from skmultilearn.adapt import MLkNN


classificador_mlknn = MLkNN(k=10,ignore_first_neighbours=0)


classificador_mlknn.fit(perguntas_treino_tfidf, tags_treino_array)

resultado_mlknn = classificador_mlknn.score(perguntas_test_tfidf, tags_teste_array)

print(f'resultado {resultado_mlknn*100:.2f}%')
previsao_mlknn = classificador_mlknn.predict(perguntas_test_tfidf)
hamming_loss_mlknn = hamming_loss(tags_teste_array, previsao_mlknn)
print(f'hamming_loss {hamming_loss_mlknn:.2f}')


C:\Users\renan\anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass n_neighbors=10 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


resultado 32.53%
hamming_loss 0.25


In [42]:
resultados_classificacao = pd.DataFrame()
resultados_classificacao['perguntas'] = perguntas_test.values
resultados_classificacao['tags real'] = list(tags_test)
resultados_classificacao['BR'] = list(previsao_br.toarray())
resultados_classificacao['cadeia'] = list(previsao_cadeia.toarray())
resultados_classificacao['mlknn'] = list(previsao_mlknn.toarray())
resultados_classificacao

perguntas     tags real  \
0     estou com conflito entre o  CODE   e os  CODE ...  (0, 1, 0, 0)   
1     Estou fazendo um site que eu sou obrigado a us...  (0, 0, 1, 0)   
2     Recentemente fiz um refactor do meu código par...  (1, 0, 0, 0)   
3     Eu tenho esse código em CODE  que passo valore...  (0, 1, 1, 0)   
4     Olá, em minha função tem o evento CODE  que de...  (0, 1, 1, 0)   
...                                                 ...           ...   
1077  Estou a desenvolver um website em jQuery. E at...  (0, 1, 0, 0)   
1078  Estou usando este plugin - jquery autocomplete...  (0, 1, 0, 0)   
1079  Tenho o seguinte jQuery:  CODE   Nisto, quanti...  (0, 1, 0, 0)   
1080  Estou usando o SimpleModal Contact Form de Eri...  (0, 1, 0, 0)   
1081  Estou tento problemas com o webpack, gostaria ...  (0, 0, 0, 1)   

                BR                cadeia         mlknn  
0     [0, 1, 0, 0]  [0.0, 1.0, 0.0, 0.0]  [0, 0, 0, 0]  
1     [0, 0, 1, 0]  [0.0, 0.0, 1.0, 0.0]  [0, 1, 1, 0]  
2     [1, 0, 0, 0]  [1.0, 0.0, 0.0, 0.0]  [1, 0, 0, 0]  
3     [0, 1, 0, 0]  [0.0, 1.0, 0.0, 0.0]  [0, 1, 1, 0]  
4     [0, 1, 0, 0]  [0.0, 1.0, 0.0, 0.0]  [0, 1, 1, 0]  
...            ...                   ...           ...  
1077  [0, 1, 1, 0]  [0.0, 1.0, 1.0, 0.0]  [0, 0, 1, 0]  
1078  [0, 1, 0, 0]  [0.0, 1.0, 0.0, 0.0]  [0, 1, 0, 0]  
1079  [0, 1, 0, 0]  [0.0, 1.0, 0.0, 0.0]  [0, 1, 0, 0]  
1080  [0, 1, 0, 0]  [0.0, 1.0, 0.0, 0.0]  [0, 1, 0, 0]  
1081  [0, 0, 0, 0]  [0.0, 0.0, 1.0, 0.0]  [0, 0, 1, 0]  

[1082 rows x 5 columns]

In [43]:
resultados_classificacao.iloc[1]

perguntas    Estou fazendo um site que eu sou obrigado a us...
tags real                                         (0, 0, 1, 0)
BR                                                [0, 0, 1, 0]
cadeia                                    [0.0, 0.0, 1.0, 0.0]
mlknn                                             [0, 1, 1, 0]
Name: 1, dtype: object

In [44]:
resultados_classificacao.perguntas[1]

'Estou fazendo um site que eu sou obrigado a usar HTML, CSS e JavaScript no máximo. Só que muitas coisas que eu preciso do PhP eu não posso usar. Sendo assim eu estive pesquisando por sinonimo de CODE  e encontrei o seguinte, que ajudou em partes:  CODE   Tá, mas qual é o problema? Ele cria uma barra de rolagem do lado. Eu sei como remover com CSS, mas o texto que foi inserido rola só dentro da área da CODE  e eu queria que fizesse como se o texto inserido fizesse parte da página, como funciona no CODE  do PhP. A questão é, como fazer a mecânica do JavaScript nesse caso ficar igual ao do PhP?  Print para exemplificar: https://imgur.com/a/V9AGLgB '